### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by wsythemes** [zurb/motion-ui#1]
Hello,

I've installed motion-ui via bower and I'm trying to create a simple animation on page load. My code is this:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Test</title>

        <link rel="stylesheet" href="bower_components/motion-ui/dist/motion-ui.min.css" media="screen">
    </head>
    <body>
        <div data-animate="slideInRight" class="slow ease">This is a div.</div>
    </body>
</html>
```

Nothing happens tho. What am I doing wrong? I've also tried compiling my own CSS, but I still can't get it to work:

```html
<div class="animated">Content</div>
```

```sass
@import "bower_components/motion-ui/src/motion-ui.scss";

@include motion-ui-transitions;
@include motion-ui-animations;

.animated {
    @include mui-animation(slide);
}
```

Can you help please?

**Comment by gakimball** [comment]
For your first example, you need to use the included JavaScript library to make the transition work. Motion UI transitions require the backing of an animation library. That `data-animate` example from the blog post is admittedly kind of misleading, so I'll go edit that. There's no hook like that built-in to the library.

For your second example, that should work, but I'm not sure why it isn't. What version of Sass are you using? And can you post the CSS that's generated from that Sass?

**Comment by wsythemes** [comment]
@gakimball  I see, ok.

For the second example, [here's a bin](http://pastebin.com/WrsgwEg8).

I'm using Sass 3.4.14.

**Comment by gakimball** [comment]
Okay, I think I see the problem. The `animation-name` property value shouldn't have quotes around it. I'll look into it shortly.
