### ISSUE TITLE
Simplifying transition-basics mixin

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/motion-ui#16]
As you set up `$duration`, `$timing` and `$delay` to `null`, there is no need to do the checks in the mixin content of [transition-basics](https://github.com/zurb/motion-ui/blob/master/src/util/_transition.scss#L12-L22).

You can change it to:

```scss
  transition-duration: $duration;
  transition-timing-function: $timing;
  transition-delay: $delay;
```

If the values are `null`, the properties won't be output.

**Comment by gakimball** [comment]
Wow, really glad I know that now. That could make elements of Foundation's codebase *way* simpler.
