### ISSUE TITLE
About the `turn` unit

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/motion-ui#17]
I am pretty sure all browsers support the `turn` unit, contrary to what is stated in the documentation from your `turn-to-deg` function. Do you have any reliable source about a browser not supporting `turn`?

**Comment by gakimball** [comment]
My source was [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/angle), which I appear to have trusted a *little* too much :) I just tested it in Chrome and Safari 8 and you're totally right. As long as it also works in iOS 8 and Android 4 we're fine.

**Comment by HugoGiraudel** [comment]
Pretty sure it works everywhere. I'll make a PR. :)

**Comment by gakimball** [comment]
Thanks, you're the best!

**Comment by gakimball** [comment]
Fixed via 47afa9d709e730ae9ab74aa38637d39b686d8e9b
