### ISSUE TITLE
Quoting strings

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/motion-ui#18]
I would advise quoting strings for improved readability as well as avoiding some very edge cases (which might never occur I must concede). Any thought?

**Comment by gakimball** [comment]
What uses of strings in particular?

**Comment by HugoGiraudel** [comment]
Any string that is not used as a CSS identifier.

**Comment by HugoGiraudel** [comment]
See #32.

**Comment by gakimball** [comment]
Sorry for not getting back to these sooner! Going to close this and #32 as we prefer our current style of using non-quoted strings as "constants". It also makes some of our APIs in this library easier to use when there are no quotes.
