### ISSUE TITLE
Javascript Delay Options

### ISSUE THREAD

**Issue by LukePettway** [zurb/motion-ui#2]
Maybe I haven't read the documentation thoroughly enough but is there a way to do animations with a delay purely using JS? I've done similar things with WOWjs and was curious if that was something that might happen down the road.

**Comment by gakimball** [comment]
The library itself doesn't currently have this feature, but you could do it using a timeout.

```js
var elem = document.querySelector('#elem');

window.setTimeout(function() {
  elem.classList.add('animate-something');
}, 1000);
```

Hard to say if it's something we want to add, because the Sass library already includes hooks for modifying core transition/animation properties like length, delay, easing, etc.

Is the advantage of doing it in JS being able to set it dynamically?

**Comment by LukePettway** [comment]
Because it is already in the Sass library, it is hard to really justify it, I was just thinking about if it would be useful to have a data attribute for setting delays that way if someone doesn't want to use Sass or needs a super fast way to add another element in a chain, they could do it. 

I did something similar on this site http://findartdoorsrva.org/ with the sponsors section where when it is scrolled into view, each image/text block loads one at a time which was easy to do because there is an attribute for delay data-wow-delay="2.5s". The nice part about this approach is that I can dynamically increment it, so as more sponsors get added, I don't have to do anything.

**Comment by gakimball** [comment]
In that case, you might want to look at how [series animations](https://github.com/zurb/motion-ui/blob/master/docs/animations.md#series-animations) work. You assign effects to elements, along with a length and delay for the next animation, and then it strings it all together for you, pre-calculating the timing of each one.

**Comment by LukePettway** [comment]
@gakimball You're right, I think that really is the best approach for the moment especially since this is really intended to be a UI centric motion library and not simply just animations. Thanks :smiley:

**Comment by gakimball** [comment]
Sounds good! And yes, UI is the focus, which is why the library is more transition-heavy at the moment.
