### ISSUE TITLE
Changing camelCase to hyphens

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/motion-ui#20]
You mostly use hyphens although there seems to be some (unexpected) exceptions such as `activateQueueClass`. Unless you have a strict naming convention explicitly stating that camelCase should be used in some scenario, I'd advise using hyphens everywhere.

**Comment by gakimball** [comment]
Yeah, that was a legacy thing where the transition classes specifically were camel case *only* for seemingly no reason.

I think we'll rip that bandaid off now and change the classes for a 1.1 release, before Foundation 6 comes out.

**Comment by HugoGiraudel** [comment]
That's very nice to hear.

**Comment by thiagotomasi** [comment]
@gakimball can I help with this issue?

**Comment by gakimball** [comment]
@thiagotomasi Go for it! All of the classes are in `src/_classes.scss`, and if there are any references to them in the docs (under `docs/src`), be sure to change them there as well.

**Comment by thiagotomasi** [comment]
@HugoGiraudel I made an PR to your suggestion! :smile: 
@gakimball Let me know if I miss something!
