### ISSUE TITLE
motion-ui using GruntJS

### ISSUE THREAD

**Issue by ochorocho** [zurb/motion-ui#3]
Hey ...

i tried to use GruntJS together with motion-ui as i do already for foundation.

so i installed the required stuff:

```
bower install motion-ui --save
npm install motion-ui --save
```
included the path in my Gruntfile.js:
```
.....
		sass: {
			options: {
				includePaths: ['bower_components/foundation/scss','bower_components/motion-ui/src']
			},
.....
```

then added motion-ui to my app.scss file:
```
@import "settings";
@import "vars";
@import "foundation";
@import "motion-ui";
@import "style";
```

When i run grunt now i get the following error:
```
Running "sass:dist" (sass) task
Verifying property sass.dist exists in config...OK
Files: scss/app.scss -> ../Styles/foundation.css
Options: precision=10, includePaths=["bower_components/foundation/scss","bower_components/motion-ui/src"], outputStyle="expanded", sourceMap=false
>> error reading values after 
>>   Line 13  Column 41  bower_components/motion-ui/src/util/_selector.scss
Warning:  Use --force to continue.

Aborted due to warnings.
```

What am i doing wrong this time? 
;-)

Thanks!

Cheers,
Jochen

**Comment by ochorocho** [comment]
hm ... 

Running this command worked for me:
```
npm install --save-dev grunt-sass
```
This updated grunt-sass the latest it seems.

**Comment by gakimball** [comment]
Yep, I was going to say that you need the absolute newest version of libsass/node-sass/grunt-sass, because a few specific things we do in the codebase were acting buggy in older versions.

**Comment by ochorocho** [comment]
Thanks for your response anyways :-)
