### ISSUE TITLE
Hinge Animation - Erratic - Firefox

### ISSUE THREAD

**Issue by blynnc** [zurb/motion-ui#36]
Hinge Animation - All variations

http://zurb.com/playground/motion-ui
and motion-ui-starter

I'm Using Firefox 41.0.1
Safari  (Version 9.0) and Chrome(45.0.2454.101) - no problem - load and function almost instantaneous

Slow to load - I stopped counting at 5 minutes.
Animation erratic. Sometimes they worked, sometimes they didn't.
At 5 minutes they still were erratic.

**Comment by gakimball** [comment]
Sorry for not getting to this sooner! We did a round of browser testing with a newer version of Motion UI and Firefox seems to be faring better. Newer versions of Firefox may have also made transition support more solid.
