### ISSUE TITLE
namespaced jQuery environments that do not use $ = jquery

### ISSUE THREAD

**Issue by RedLucas** [zurb/motion-ui#38]
In certain environments such as Drupal, the $ is not used as an alias for jQuery. This makes Motion-UI not work. I suggest this solution to fix the problem https://github.com/RedLucas/MotionUI/commit/b0d57ad672f90ff4e4da5e6922200dfa8dc41690

**Comment by gakimball** [comment]
Try using the file `dist/motion-ui.js`. It has a UMD wrapper which also references `jQuery` instead of `$`.

**Comment by gakimball** [comment]
Closing this as I believe the above solution will fix your problem. You can see on [this line](https://github.com/zurb/motion-ui/blob/master/dist/motion-ui.js#L7) the plugin is referencing `root.jQuery`, where `root` is `window`.
