### ISSUE TITLE
SVG won't animate via MotionUI.animateIn($elem, 'spin');

### ISSUE THREAD

**Issue by JoeNoPhoto** [zurb/motion-ui#43]
```html
<svg>
  <g class="logo-frame bounceInOut">

```

```javascript 
var $elem = $('logo-frame');
MotionUI.animateIn($elem, 'spin');
```

I can't seem to get ```MotionUI.animateIn($elem, 'spin')``` to run on my ```<g class="logo-frame">``` tag. It doesn't work on the ```<path>``` tag either. If I try ```<li class='logo-frame'>``` the animation will run properly. 

I've been doing a bit of looking around and it seems that addClass doesn't play nicely with ```<svg>```,so I assume that has something to do with it? I was able to add a class to svg using [this module](https://github.com/toddmotto/lunar). It's native javascript, but I was able to convert it to jquery as well.

I was able to use the ```@include mui-series``` and ```@include mui-queue``` mixins in scss and I am able to add ```is-animation``` to the container.

**Comment by gakimball** [comment]
Hey, really sorry for not getting to this sooner! Awesome that you were able to get it working. :)

Since Motion UI is focused on UI component animation, we won't likely add support for SVG in the near future, but it's always a possibility.

**Comment by gakimball** [comment]
FYI, [jQuery 2.2](https://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/), which was released last week, added supported for class manipulation on SVGs!
