### ISSUE TITLE
No animate with css class

### ISSUE THREAD

**Issue by baaboum** [zurb/motion-ui#46]
Hello, i arrive to make animation with js but if i use class, animations don't work.

This code work 
```javascript
$(function() {
        var $yeti = $('.plop');
        var $transitionList = $('#transitionList');

        $('.butonplap').click(function() {
            MotionUI.animateIn($yeti, $transitionList.val());
        });
    });

```

If i had class with jquery, animation don't work (compilation with grunt-sass is good)
```javascript
$button.click(function() {
        $panel.addClass('wiggle');
    });
```
outpout css in firebug
```css
.wiggle {
    animation-name: wiggle-7deg;
}
```

I don't understand the problem, so is there somebody who can help me please?.

Thanks for your help

**Comment by ochorocho** [comment]
@baaboum, i already asked this question i think:
https://github.com/zurb/motion-ui/issues/37#issuecomment-152158338

so basically you need to add a class for duration as well:
e.g.

.myelement{
   -webkit-animation-duration: 5s
}

**Comment by baaboum** [comment]
Oops i haven'n see thanks a lot for your help :)
