### ISSUE TITLE
How can I animate a dropdown menu using motion-ui?

### ISSUE THREAD

**Issue by imaia** [zurb/motion-ui#50]
Hello folks. I would like to change my dropdown default behavior on hover (just appear) to something prettier, like a fade-in/fade-out or something like that. Can I use motion-ui for this task? I'm using foundation-sites

**Comment by gakimball** [comment]
@imaia Dropdown menus don't support Motion UI at the moment, but I'll add it to our internal roadmap for Foundation for Sites. We'll be publishing this roadmap soon, so the community can review it and get involved if they want.

Thanks for the suggestion! :)

**Comment by anephew** [comment]
Hello! Any news on this feature?

Thank you

**Comment by reeslo** [comment]
+1

**Comment by anephew** [comment]
Hey, I solved the problem, you can see an [example](https://codepen.io/anephew/pen/VpWRRX)

Just using [dropdown events](http://foundation.zurb.com/sites/docs/dropdown-menu.html#js-events) and a bit of jquery animation. In any case, I would like to see the settings from the box

**Comment by reeslo** [comment]
thanks for sharing I've tête see this method on zurb forum.
