### ISSUE TITLE
MotionUI.animateOut, MotionUI.animateOut do not work properly

### ISSUE THREAD

**Issue by baaboum** [zurb/motion-ui#51]
Hello,

I get a problem using motion-ui. I have 4 div on which I want to use it but when the mouse goes out before the animation is finished everything messes up. I searched the web and could not find exact answer to this problem as it's said to use the stop() method but it is not implemented. Is there any workaround ?

Thanks for your help.

```javascript
$(".hover_service").each(function() {

        var $titre = $(this).find('.titre');
        var $content = $(this).find('.content');

        $(this).mouseenter(function() {
            MotionUI.animateOut($titre, 'slide-right-out');
            MotionUI.animateOut($content, 'slide-left-in');
        });

        $(this).mouseleave(function () {
            MotionUI.animateIn($titre, 'slide-right-in');
            MotionUI.animateOut($content, 'slide-right-out');
        });
    });
```

**Comment by gakimball** [comment]
Hey @baaboum, sorry for the late response.

First off, looking at your code sample, in the `mouseenter` event handler you use `MotionUI.animateOut` to add `.slide-left-in`, an "in" transition. Did you mean to use `animateIn`?

Motion UI doesn't have any hooks for canceling a transition in progress, although maybe it's worth looking into. You mention a `.stop()` method that some research led you to, what is this `.stop()` method for?

**Comment by realchriswells** [comment]
I have a similar issue with animateIn and animateOut in that they don't see to work.

I have this code:
```
var dropdown = $j('.all-watches .dropdown');

    $j('.all-watches a').on('click', function () {
        if (dropdown.hasClass('open')) {
            dropdown.removeClass('open');
            MotionUI.animateOut(dropdown, 'fade-out', function() {
                console.log('Transition finished!');
            });
        } else {
            dropdown.addClass('open');
            MotionUI.animateIn(dropdown, 'fade-in', function() {
                console.log('Transition finished!');
            });
        }
    });
```

and this markup:
```
<ul>
        <li class="all-watches">
            <a href="javascript:;" title="All Watches">All Watches</a>
        </li>
    </ul>
    <div class="dropdown">
        <div class="dropdown--wrapper">
            ...
        </div>
    </div>
```

The markup above becomes this when triggered:
```
<ul>
        <li class="all-watches">
            <a href="javascript:;" title="All Watches">All Watches</a>
        </li>
    </ul>
    <div class="dropdown open fade-in mui-enter mui-enter-active" style="display: block;">
        <div class="dropdown--wrapper">
            ...
        </div>
    </div>
```
and the .dropdown div fades in nicely. But when I try to trigger the same thing to make it go away, all that happens is the markup changes to this:

```
<ul>
        <li class="all-watches">
            <a href="javascript:;" title="All Watches">All Watches</a>
        </li>
    </ul>
    <div class="dropdown fade-in mui-enter mui-enter-active fade-out mui-leave mui-leave-active" style="display: block;">
        <div class="dropdown--wrapper">
            ...
        </div>
    </div>
```

Is this a bug, or am I just being really dumb? I hope I'm being dumb.

**Comment by gakimball** [comment]
@realchriswells It looks like Motion UI isn't properly cleaning up the transition classes after the fade in.

By the way, are you using this with Foundation? Try swapping out `MotionUI` with `Foundation.Motion` and see if it works better. Foundation's motion module is better developed.
