### ISSUE TITLE
How i can use motion ui animation on things while page scroll ?

### ISSUE THREAD

**Issue by hassanbinsafdar** [zurb/motion-ui#52]
I want to animate things while page scrolling is it possible or no ? I want to use this with foundation 6

**Comment by gakimball** [comment]
Hey, sorry for the late response! Motion UI doesn't include this feature out of the box, but you can integrate it with WOW.js. [I wrote a post on the Foundation Forum](http://foundation.zurb.com/forum/posts/36285-motion-ui-on-scroll) explaining how it works. Hope that helps! :)

**Comment by gakimball** [comment]
Opening an issue to track adding WOW.js integration to the Motion UI documentation: #63
