### ISSUE TITLE
how to use motion-ui scss for beginners?

### ISSUE THREAD

**Issue by rlynjb** [zurb/motion-ui#55]
hi all, i was wondering how can i use motion-ui without javascript. 

so far, i've added fade-in class name on my h1 tag but it doesnt seem to fade in..
i've imported and inlcuded motion-ui and motion-ui-transitions and motion-ui-animations on my scss file but still no luck.. am i missing something here? sorry.. i'm just really new to using zurb motion-ui feature

**Comment by gakimball** [comment]
You could use the animations without JavaScript, but not the transitions.

For the most part, though, this library is specifically designed to be paired with a JavaScript animation library, such as Foundation 6's, Angular's angular-animate, or React's animation module.

I see you closed the issue already, but if you still need help let us know :)

**Comment by rlynjb** [comment]
ah thank you for responding @gakimball I kind of figured that would be the case.
