### ISSUE TITLE
possible bug on $motion-ui-settings custom configuration

### ISSUE THREAD

**Issue by rlynjb** [zurb/motion-ui#56]
hi guys,
I have added this code

$motion-ui-settings: (                 
  slide-and-fade: true,                
  hinge-and-fade: true,                
  scale-and-fade: true,                
  spin-and-fade: true,                 
  activate-queue-class: 'is-animating' 
);                                     

on my app-custom.scss file hoping to have a fade in transition included on a slide-in-left transition i was using but it doesn't seem to work.

I've ran gulp to make to it re-builds my file but still no luck.
My temporary work around was this

@include mui-slide( 
  $fade: true       
);                  

and it works perfect.

**Comment by gakimball** [comment]
Strange, here's where it gets the default that should apply: <https://github.com/zurb/motion-ui/blob/master/src/transitions/_slide.scss#L13>

Looking into it!

**Comment by rlynjb** [comment]
hi @gakimball looking into this issue as well and thank you for pointing me to  https://github.com/zurb/motion-ui/blob/master/src/transitions/_slide.scss#L13

I've looked into what map-get does and it turns out that when I make the settings change under my /bower_components/motion-ui/src/_settings.scss file.. the change goes through..

I think the error is on my /src/assets/scss/app-cusotm.scss files when I try to override $motion-ui-settings mixin from there..

sorry I am so new to this and I am still finding my way around sass

**Comment by gakimball** [comment]
@rlynjb Yes! Good catch. This is something we don't fully address right now.

I wouldn't recommend editing the `_settings.scss` file in the Motion UI package. When we release a new version, if you update, that file will get replaced with a new copy.

Instead, try changing those Motion UI settings *before* the line `@import 'motion-ui';` in your code. That way the settings will apply before the framework is loaded, which should apply them properly.

**Comment by rlynjb** [comment]
thanks for that info @gakimball 
its working now as it should! :-D
i was just wondering why do we need to place the 'motion-ui-settings' code before '@import 'motion-ui';'?
i am just trying to see how sass works in an order of loading its files.

**Comment by gakimball** [comment]
It's a quirk with how Sass works, we tend to load the configuration before the library is initialized.

If you look where the settings are defined in the library itself, each one is tagged with `!default`. Normally in a programming language, if you define the same variable twice, the value it uses will be the one you defined the second time.

In Sass, you can do *guarded assignment*, which means a variable tagged with `!default` won't override a variable if you already set it. We use this feature for library settings.

```scss
$setting: true;

$setting: false !default;

// The value of $setting is still true
```

**Comment by rlynjb** [comment]
ha awesome thanks @gakimball for this.. that clarifies things now on how to go around settings and files..
