### ISSUE TITLE
Extend defaults - change to mixin?

### ISSUE THREAD

**Issue by brettsmason** [zurb/motion-ui#58]
Is it possible to change the extend defaults (%mui-defaults) to a mixin? This seems to resolve the issue I was having with this being output at the top of my stylesheet. This was mentioned in an issue I raised for Foundation [7641](https://github.com/zurb/foundation-sites/issues/7641).

I'll put together a PR and see what you think!

**Comment by gakimball** [comment]
I liked that approach because it kept the file size down, but I'm definitely not in love with the extended CSS appearing at the top of the stylesheet.

Could you compare the file size of the CSS before and after this change? Run `npm start dist` to regenerate the dist files.

**Comment by brettsmason** [comment]
The filesizes on the PR are:
normal - 21kb
minified - 16kb

**Comment by gakimball** [comment]
Hm, we can probably live with 2KB. We actually shaved 1KB off of Foundation from 6.0 to 6.1!

**Comment by brettsmason** [comment]
I love trimming size too but I agree, think its worth it :smile: 
By the way loved your article in Net magazine on Motion UI, very helpful :+1:

**Comment by gakimball** [comment]
Thanks! :)

Merged #59
