### ISSUE TITLE
Cannot get transitions to work

### ISSUE THREAD

**Issue by rogersmj** [zurb/motion-ui#60]
I have a raw Foundation 6 project (created with the foundation CLI), and I followed the docs here to enable motion-ui. It is installed via bower, and I can see the CSS compiled into the output css file used by my static single page site.

However, I cannot get ANY transitions to work. I have read the relevant pages of the docs a dozen times, and I don't know what I'm missing. But animations DO work. For example, trying to fade something in:

```
<h2 class="fade-in slow">Some text</h2>
```

does absolutely nothing.

But this works:

```
<h2 class="wiggle slow">Some text</h2>
```

I have also tried using the mix-in method, instead of applying a CSS class directly to the HTML element. Same behavior: animations work, transitions do not. I have tried this on text an images. There are no errors being thrown by my CSS/JS compiler or the browser console (Chrome on a Mac). This is driving me nuts, can someone please help?

**Comment by sonicpunk** [comment]
I am having the same issue.  The motion ui is working on Foundation plugins, but I am having difficulty getting it to work on my own elements.  

I installed motion-ui via bower, added it to my main sass file along with foundation, and as I said, it is working with Foundation.  

I can also add mixins from motion-ui to classes in my sass file without errors and the css gets properly written, but nothing gets triggered.

I also have included the motion-ui.js to the project.  

I tried the class example above and wiggle is working

´<p class="primary wiggle slow">Neues Album 'Nachtmensch'</p>´

I also am getting no errors from my compiler

**Comment by clearsitedesigns** [comment]
I seem to be having this same issue. I try to apply an animation to element like above but fade is not working. Wiggle did work.

**Comment by fheinrichs** [comment]
Did you invoke the transition in JS? I mean, did you do somewhere something like

    MotionUI.animateIn('#element', 'fade-in');

for instance bind it to a clickable element like so

    $('#myElement').onClick(function () { MotionUI.animateIn(this, 'fade-in');});

It's not very clearly pointed out in the docs, but while animation only requires the appropriate class, you have to invoke transition through the `MotionUI.animateIn` or `MotionUI.animateOut` functions.

**Comment by imaginethepoet** [comment]
No I did not. I was assuming that some of the transitions for motion could just be applied to an element without invoking it via javascript (similar to how animate.css works). Sometimes I just want a simple animation and not a chained effect with a click event.

**Comment by gakimball** [comment]
@imaginethepoet This library was deliberately designed for JavaScript animation libraries, which is why it has a transition focus. The built-in classes are all transitions, but you can use those same effects as animations with the `mui-animate()` mixin. [Here are the docs for creating animations.](https://github.com/zurb/motion-ui/blob/master/docs/animations.md)

**Comment by imaginethepoet** [comment]
I totally missed the part that said you needed to have  an "animation-duration."  After that mix-ins were working fine. 

Thanks

**Comment by gakimball** [comment]
@rogersmj Going to close this as I believe you have the answers you need. At the moment CSS animations sort of take a back seat to transitions—all of the core effects have *transition* classes, but not *animation* classes. However, you can make them yourself with this syntax:

```scss
.animate-fade-in {
  @include mui-animation(fade);
}
```

[Refer to the documentation on animation to learn more.](https://github.com/zurb/motion-ui/blob/master/docs/animations.md) I think in the future we can look at adding more drop-in animation classes as an option.
