### ISSUE TITLE
Meteor Package

### ISSUE THREAD

**Issue by merlinpatt** [zurb/motion-ui#71]
Are there plans to publish a Meteor package for Motion UI?

**Comment by gakimball** [comment]
If you want to implement it, we'll accept a pull request for it.

It's worth noting, also, that with Meteor 1.3 supporting npm out of the box, a dedicated package will be less necessary soon.

**Comment by juliancwirko** [comment]
I think that we can create meteor package and remove motion-ui dependencies in foundation package. This motion-ui dependency breaks the foundation package in Meteor 1.3 and for now there isn't a way to import and compile scss files from node_modules in Meteor 1.3 (unfortunatelly this is a blocker in the context of many npm packages :/) so if there will be no such possibility in the final 1.3 we will still need meteor package for foundation. 

I'll try to create PR for zurb:motion-ui and then I'll edit foundation package (there are some files structure/names changes and then I remove motion-ui dependency in zurb:foundation-sites. We can add week dependency if there will be zurb:motion-ui published in the Atmoshpere).

**Comment by gakimball** [comment]
Merged #73 and published new Meteor package: 9891cb731db5b892db76a1d563054cd2eff03410
