### ISSUE TITLE
Motion-UI of Reveal

### ISSUE THREAD

**Issue by javatheist** [zurb/motion-ui#75]
I ran into a scope issue with Motion-UI when trying to close a Reveal-Box.

`Foundation.Motion.animateIn(this.$element, this.options.animationIn, function () {
            this.focusableElements = Foundation.Keyboard.findFocusable(this.$element);
          });`

The line with "findFocusable" should have '_this2.$element' instead of "this.$element" as "this" refers to jQuery-Item of the Reveal-Box itself, thus breaking the closing routine with `Uncaught TypeError: Cannot read property 'find' of undefined`

hth, Peter

**Comment by gitnik** [comment]
Any idea when this will be released? This is pretty much blocking our usage of animated reveals for now.

**Comment by gakimball** [comment]
@gitnik We'll try to prep a patch in the next few weeks, right now the team is heads-down on the impending launch of [Foundation for Emails 2](https://github.com/zurb/foundation-emails).
