### ISSUE TITLE
dist folder is not updated!

### ISSUE THREAD

**Issue by abdullahsalem** [zurb/motion-ui#77]
@gakimball Regarding to this commit https://github.com/zurb/motion-ui/commit/2c8d2bb230fbc1784dcf6ae1931238c7802d75ce , the folder `dist` still contains the build of version 1.2.0, but it should contain the build of version 1.2.2

**Comment by gakimball** [comment]
I'm guessing you caught this, but the CSS itself didn't change between 1.2.0 and 1.2.2.
