### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery'

### ISSUE THREAD

**Issue by kevster** [zurb/motion-ui#81]
I installed Motion UI via `meteor add zurb:motion-ui`, but when I start meteor (tried 1.3.2 and 1.3.3) I get the following client error:

> Uncaught Error: Cannot find module 'jquery'
> require @ install.js:78
> (anonymous function) @ motion-ui.js:5
> meteorInstall.node_modules.meteor.zurb:motion-ui.dist.motion-ui.js @ motion-ui.js:1
> fileEvaluate @ install.js:141
> require @ install.js:75
> (anonymous function) @ zurb_motion-ui.js?hash=7f54557…:171
> (anonymous function) @ zurb_motion-ui.js?hash=7f54557…:177`

jquery seems to work fine though, but Motion UI does not.

**Comment by benlime** [comment]
Same issue for me. +1

**Comment by kevster** [comment]
@benlime did you ever figure out a solution? seems like this repo is pretty dead

**Comment by benlime** [comment]
@kevster ended up using animate.css - maybe using the npm version of motion-ui will work. Try that instead.
