### ISSUE TITLE
ReferenceError: "Can't find variable: MotionUI"

### ISSUE THREAD

**Issue by ldesmarets** [zurb/motion-ui#82]
Hello,

i'm trying a simple javascript within a Yeti Launch project, using MotionUi in javascript
i get this error "ReferenceError: "Can't find variable: MotionUI"

When i read the app.js file i've got a variable MotionUI but i get the error anyway.

hers's the code

```
$(document).foundation();

//Animate menu panel on right with MOTION.UI
MotionUI.animateOut('#sliding-panel', 'fadeOut fast');
MotionUI.animateIn('#main-logo', 'fade-in slow 7800', function() {
});
```

Best regards

**Comment by ncoden** [comment]
> 21 Jul 2016

It seems to be an import issue on your side. We cannot help that much on this. This issue is almost 2 years old, so I'm closing it as you probably found a solution since then. 😉
