### ISSUE TITLE
Explictly stating 'from' and 'to' parameters for fade-out

### ISSUE THREAD

**Issue by thealkimist** [zurb/motion-ui#83]
Took me sometime to realize that when declaring a mixin like `mui-fade($state: out, $duration: 200ms)`, one had to also explicitly state `$from` and `$to`. Not sure if other animation features have this same issue, but in this case defining `$state: out` should be enough to execute `out`.

**Comment by ncoden** [comment]
See https://github.com/zurb/motion-ui/pull/103
