### ISSUE TITLE
Meteor 1.4 not working

### ISSUE THREAD

**Issue by julian-rare** [zurb/motion-ui#89]
I'm trying to use 

https://atmospherejs.com/zurb/motion-ui

by running

` meteor add zurb:motion-ui`

and adding the sass file:
`@import '{zurb:motion-ui}/src/motion-ui';`

But the basic orbit example works with motion turned off, once I enable it, just freezes after click on the 2nd slide.

But if I just include manually the motion-ui.min.css it works.

**Comment by anjunatic** [comment]
Same problem! Same thing happen also with package imported from npm.

**Comment by ncoden** [comment]
You need to include Sass mixins:
```scss
@include motion-ui-transitions;
@include motion-ui-animations;
```

I updated the Meteor installation instructions

**Comment by ncoden** [comment]
See https://github.com/zurb/motion-ui/pull/120
