### ISSUE TITLE
Invalid CSS value in _fade.scss using GulpSASS

### ISSUE THREAD

**Issue by dherran** [zurb/motion-ui#91]
When compiling using gulp-sass 3.1.0 it throws the following error:

```
{ Error: node_modules\motion-ui\src\effects\_fade.scss
Error: (name: "fade-cyan-to-5000%", 0: (opacity: #08c), 100: (opacity: 50%)) isn't a valid CSS value.
        on line 26 of node_modules/motion-ui/src/effects/_fade.scss
>>     name: 'fade-#{$fromName}-to-#{$toName}',
```

Any ideas?

**Comment by kball** [comment]
I think the problem is the arguments being passed... looking at the file in question it looks like it is expecting two values between `0` and `1`, while judging from the error it looks like you may have passed `50%`.  Can you try passing `0.5` instead?

**Comment by dherran** [comment]
I am not passing any values though. I simply included the motion-ui SASS file into my Foundation project like so:

`@import 'motion-ui';`

And it crashes immediately. Are Foundation settings passed down to motion-ui?

**Comment by pixelimp** [comment]
Having the same issue on my end.

**Comment by kball** [comment]
@dherran @pixelimp This is odd, as the details of that error don't look like any of the variables passed to that function by default... it looks as though something is including @mui-fade (or calling the underlying fade function) with invalid arguments...  I just tried a vanilla compile with the ZURB template updated to gulp-sass 3.1.0 without any problems, so I'm still believing that as the most likely explanation

Is there any way you could give me access to see the project in question?

**Comment by dherran** [comment]
@kball thanks Kev for looking into this.

In my case the issue was due to React Select calling a fade() function from within their SASS files. They fixed this issue however in their latest commit.

https://github.com/JedWatson/react-select/commit/9150107a6a463f561f5b3b839c74c24ca8be6f8a#diff-83c485d33aaac203f25c11cbac20b171L15
